version: '3.7'

services:
  confluence:
    image: ghcr.io/declue/confluence:8.2.3
    env_file:
      - ".env"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFLUENCE_VERSION: $CONFLUENCE_VERSION
    container_name: confluence
    ports:
      - "8090:8090"
    volumes:
      - ./data:/var/atlassian/confluence
    logging:
      driver: "json-file"
      options:
          max-size: "100m"
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: confluence
      TZ: Asia/Seoul
    volumes:
     - "./db/conf.d:/etc/mysql/conf.d"
     - "./db/data:/var/lib/mysql"
     - "./db/initdb.d:/docker-entrypoint-initdb.d"


