version: '3.1'

services:
  confluence:
    build: .
    image: declue/confluence:6.15.7
    container_name: myconfluence
    ports:
      - "8090:8090"
    volumes:
      - ./certs:/etc/certs
      - ./data:/var/atlassian/confluence
    logging:
      driver: "json-file"
      options:
          max-size: "100m"
